---
- name: Configurar firewalld en el servidor web
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_facts['os_family'] == 'RedHat'

- name: Configurar UFW en el servidor de base de datos
  ansible.builtin.include_tasks: debian.yml
  when: ansible_facts['os_family'] == 'Debian'
