---
- name: Validar el servidor de base de datos
  ansible.builtin.include_tasks: db.yml
  when: inventory_hostname == 'db'

- name: Validar el servidor de aplicacion
  ansible.builtin.include_tasks: web.yml
  when: inventory_hostname == 'web'
